ci:
  autofix_commit_msg: |
      [pre-commit.ci] auto fixes from pre-commit.com hooks
      for more information, see https://pre-commit.ci
  autofix_prs: true
  autoupdate_branch: ''
  autoupdate_commit_msg: '[pre-commit.ci] pre-commit autoupdate'
  autoupdate_schedule: quarterly
  skip: []
  submodules: false

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-yaml
      - id: check-added-large-files
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.22
    hooks:
      - id: ruff-check
        types_or: [ python, pyi ]
        args: [ --fix ]
      - id: ruff-format
        types_or: [ python, pyi ]
  - repo: local
    hooks:
      - id: mypy
        name: running mypy
        entry: mypy
        language: system
        types: [python]
      - id: pytest
        name: running pytest
        entry: pytest --cov=src
        language: system
        pass_filenames: false
